In [1]:
import sklearn
import seaborn as sn
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading & Reading the dataset
df=pd.read_csv('creditcard.csv')

In [12]:
#Checking uploaded dataset
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

In [5]:
df.ndim

2

In [6]:
# Describing the data columns wise
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.919560e-15  5.688174e-16 -8.769071e-15  2.782312e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552563e-15  2.010663e-15 -1.694249e-15 -1.927028e-16 -3.137024e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.537294e-16  7.959909e-16  5.367590e-16  4.458112e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.453003e-15  1.699104e-15 -3.660161e-16 -1.206049e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [9]:
# Checking Data type of each columns 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [13]:
# checking the any Null value in dataset
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

- there no Null values in Dataset

In [14]:
# Counting the normal transactions and fraud trandaction
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

- Here 0 represents the normal transactions and 1 represents fraud transactions
- And we can see that, this is imbalanced dataset as there are two types of target variables and from that more than 98 to 99% of the data is present in the first variabel only
- And for that we can use different techniques to deal with the imbalance dataset like under sampling or over sampling

# Performing the training and testing so that we can build our model

##### So, now we will store the independent and dependent variable into new variable

In [17]:
# storing the independent and dependent features in x & y variable
x=df.drop(['Class'], axis=1)
y=df['Class']

In [18]:
x.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [19]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

##### now we will split the dataset into training and testing

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [22]:
x_train.head()

Time        V1        V2        V3        V4        V5        V6  \
2557      2105.0 -2.289565 -0.480260  0.818685 -1.706423  0.822102 -1.660326   
247823  153702.0 -0.313717 -4.064342 -3.398445  0.704011  0.101662  1.529848   
152342   97283.0 -1.809763 -0.567439  2.265186 -0.960318 -1.212537  1.516493   
103385   68628.0  1.192319  0.178575  0.141491  0.459628 -0.049959 -0.112122   
8771     11951.0 -0.963451  0.700311  1.097333 -1.547626  0.669966  0.513533   

              V7        V8        V9  ...       V20       V21       V22  \
2557    0.944047 -0.541765  1.323156  ... -0.831985 -0.210837  0.914737   
247823  1.551670 -0.036774  0.015829  ...  2.142593  0.853186 -0.091941   
152342 -1.417176  0.903421  1.961027  ... -0.554004 -0.509915 -0.424978   
103385 -0.163883  0.155740 -0.067566  ... -0.149985 -0.240464 -0.739862   
8771    0.333683  0.270900  1.381880  ...  0.122458 -0.279519 -0.470181   

             V23       V24       V25       V26       V27       V28   Amount  
2557    0.867888  0.422969  0.310584 -0.781488  0.392241 -0.147757     1.00  
247823 -0.936215 -0.833081 -0.498728  0.651183 -0.290331  0.110360  1194.28  
152342 -0.268621  0.010121  0.466862  0.835540 -0.062385  0.088079    75.00  
103385  0.116799 -0.373837  0.125470  0.130126 -0.016956  0.011937     1.98  
8771   -0.124037 -1.388839 -0.237453  0.785347  0.349708  0.216207    37.31  

[5 rows x 30 columns]

In [23]:
x_test.head()

Time         V1        V2         V3        V4         V5  \
43428    41505.0 -16.526507  8.584972 -18.649853  9.505594 -13.793819   
49906    44261.0   0.339812 -2.743745  -0.134070 -1.385729  -1.451413   
29474    35484.0   1.399590 -0.590701   0.168619 -1.029950  -0.539806   
276481  167123.0  -0.432071  1.647895  -1.669361 -0.349504   0.785785   
278846  168473.0   2.014160 -0.137394  -1.015839  0.327269  -0.182179   

              V6         V7        V8        V9  ...       V20       V21  \
43428  -2.832404 -16.701694  7.517344 -8.507059  ... -1.514923  1.190739   
49906   1.015887  -0.524379  0.224060  0.899746  ...  0.506044 -0.213436   
29474   0.040444  -0.712567  0.002299 -0.971747  ...  0.212877  0.102398   
276481 -0.630647   0.276990  0.586025 -0.484715  ... -0.244633  0.358932   
278846 -0.956571   0.043241 -0.160746  0.363241  ... -0.255293 -0.238644   

             V22       V23       V24       V25       V26       V27       V28  \
43428  -1.127670 -2.358579  0.673461 -1.413700 -0.462762 -2.018575 -1.042804   
49906  -0.942525 -0.526819 -1.156992  0.311211 -0.746647  0.040996  0.102038   
29474   0.168269 -0.166639 -0.810250  0.505083 -0.232340  0.011409  0.004634   
276481  0.873663 -0.178642 -0.017171 -0.207392 -0.157756 -0.237386  0.001934   
278846 -0.616400  0.347045  0.061561 -0.360196  0.174730 -0.078043 -0.070571   

        Amount  
43428   364.19  
49906   520.12  
29474    31.00  
276481    1.50  
278846    0.89  

[5 rows x 30 columns]

In [24]:
y_train.head()

2557      0
247823    0
152342    0
103385    0
8771      0
Name: Class, dtype: int64

In [25]:
y_test.head()

43428     1
49906     0
29474     0
276481    0
278846    0
Name: Class, dtype: int64

# Logistict Regression

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
lr=LogisticRegression()

In [28]:
lr

LogisticRegression()

In [29]:
lr.fit(x_train,y_train)

LogisticRegression()

In [30]:
y_pred=lr.predict(x_test)

In [33]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [34]:
# checking the accuracy on training data
y_pred_train=lr.predict(x_train)
training_data_accuracy = accuracy_score(y_pred_train,y_train)
print('Training Dataset Accuracy',training_data_accuracy)

Training Dataset Accuracy 0.9987861399249613


In [35]:
# checking the accuracy on test data
accuracy_score(y_test,y_pred)

0.9987828142738434

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.61      0.64      0.63       136

    accuracy                           1.00     85443
   macro avg       0.81      0.82      0.81     85443
weighted avg       1.00      1.00      1.00     85443



In [37]:
confusion_matrix(y_test,y_pred)

array([[85252,    55],
       [   49,    87]], dtype=int64)

- Now, after this we can see the confusion matrix that, TP(True Positive) records are high and TN(True Nigative) records are low   but the FN(False Nigative) and FP(False Positive) records are low
- And our main goal is to lower the value of the FN(False Nigative) and FP(False Positive)
- And for that we can use different techniques and as our dataset is imbalance so here we can use different sampling techniques

##### Now we will use CV and some hyperparameter to deal with this data and then I will check the new score of the model

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import RandomizedSearchCV

In [40]:
Log_Class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3), 'penalty':['l1','l2']}
cv = KFold(n_splits=5,random_state=None, shuffle=False)

In [42]:
LC= GridSearchCV(Log_Class, grid,cv=cv,n_jobs=-1,scoring='f1_macro')

In [43]:
LC.fit(x_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [44]:
y_predgrid = LC.predict(x_test)
print(confusion_matrix(y_test,y_predgrid))
print(accuracy_score(y_test,y_predgrid))
print(classification_report(y_test,y_predgrid))

[[85268    39]
 [   55    81]]
0.9988998513628969
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.68      0.60      0.63       136

    accuracy                           1.00     85443
   macro avg       0.84      0.80      0.82     85443
weighted avg       1.00      1.00      1.00     85443



# RandomForest Classifier

In [45]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(x_train, y_train)

RandomForestClassifier()

In [46]:
# checking the accuracy on training data
y_train_RFC = RFC.predict(x_train)
training_data_accuracy = accuracy_score(y_train_RFC,y_train)
print('Training Dataset Accuracy', training_data_accuracy)

Training Dataset Accuracy 0.9999949840492767


In [47]:
# accuracy score and classification report of the Random Forest
y_pred_RFC = RFC.predict(x_test)
print(confusion_matrix(y_test,y_pred_RFC))
print(accuracy_score(y_test,y_pred_RFC))
print(classification_report(y_test,y_pred_RFC))

[[85302     5]
 [   27   109]]
0.9996254813150287
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.96      0.80      0.87       136

    accuracy                           1.00     85443
   macro avg       0.98      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443



## Now, I will use oversampling and then use the Random Forest Classifier model to check the score again and I will check again the FN and FP

In [48]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

In [51]:
ROS = RandomOverSampler(0.75)
x_train_ros, y_train_ros = ROS.fit_resample(x_train, y_train)
print("The number of classes before fit{}".format(Counter(y_train)))
print("The number of classes after fit{}".format(Counter(y_train_ros)))

The number of classes before fitCounter({0: 199008, 1: 356})
The number of classes after fitCounter({0: 199008, 1: 149256})


In [53]:
from sklearn.ensemble import RandomForestClassifier
OS_RFC_Classifier = RandomForestClassifier()
OS_RFC_Classifier.fit(x_train_ros, y_train_ros)

RandomForestClassifier()

In [54]:
y_pred_OS_RFC = OS_RFC_Classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred_OS_RFC))
print(accuracy_score(y_test,y_pred_OS_RFC))
print(classification_report(y_test,y_pred_OS_RFC))

[[85302     5]
 [   26   110]]
0.9996371850239341
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.96      0.81      0.88       136

    accuracy                           1.00     85443
   macro avg       0.98      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443

